### ISSUE TITLE
Singleton does not work

### ISSUE THREAD

**Issue by krwu** [spiral/framework#263]
I tried to implement singleton service like this:

```php
// AppBootloader.php:
use App\Service\MyService;
use Spiral\Boot\Bootloader\Bootloader;

class AppBootloader extends Bootloader
{
    protected const SINGLETONS = [
        MyService::class => MyService::class,
    ];
}
```

```php
// MyService.php
class MyService
{
    // use ProtoTypeTrait;

    protected static $count = 0;
    protected $count2 = 0;

    public function getCount(): int
    {
        if (static::$count === 0) {
            static::$count = 1;
            // $this->logger->debug('count init');
        } else {
            static::$count += 1;
        }
        return static::$count;
    }

    public function getCount2(): int
    {
        if ($this->count2 === 0) {
            $this->count2 = 1;
            // $this->logger->debug('count2 init');
        } else {
            $this->count2 += 1;
        }
        return $this->count2;
    }
}
```

```php
// HomeController.php

public function count(MyService $svc): int
{
    return $svc->getCount();
}

public function count2(MyService $svc): int
{
    return $svc->getCount2();
}
```

No matter how many times I visit `http://localhost:8080/count.html` or `http://localhost:8080/count2.html`, the output always `1`. If I enable debug logger, each time I visit the url, a new line "DEBUG: count init" or "DEBUG: count2 init" will append to the log file.

I also tried to make `MyService` implements `SingletonInterface`, it does not work either.

How should I do?

**Comment by wolfy-j** [comment]
Hi, What is your rr config?

**Comment by krwu** [comment]
```yaml
http:
  address: localhost:8080

  workers:
    command: "php app.php"
    pool.numWorkers: 1
    pool.maxJobs: 1

# queue and jobs
jobs:
  dispatch:
    app-job-*.pipeline: "local"
  pipelines:
    local:
      broker: "ephemeral"
  consume: ["local"]

  workers:
    command: "php app.php"
    # pool.numWorkers: 1
    # pool.maxJobs: 1

# serve static files
static:
  dir:    "public"
  forbid: [".php", ".htaccess"]

# metrics:
# prometheus client address (path /metrics added automatically)
#  address: localhost:2112

# control the max memory usage
limit:
  services:
    http.maxMemory: 100
    jobs.maxMemory: 100
```

**Comment by wolfy-j** [comment]
MaxJobs:1, your workers die after every request. Singletons in this mode won’t work.

**Comment by krwu** [comment]
After I commented the two lines:

```yaml
http:
  address: localhost:8080

  workers:
    command: "php app.php"
    # pool.numWorkers: 1
    # pool.maxJobs: 1
```

I can see there are 12 workers. Then, the number will change once after I refresh the page for 12 times...
